name: pretty_button
description: Flutter pretty and customizable 3D button with minimal design and highly customizable.It can be also disabled.
version: 0.0.7
repository: https://github.com/Dharti1623/prettyButtons
homepage: https://github.com/Dharti1623

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.pretty_button
        pluginClass: PrettyButtonPlugin
      ios:
        pluginClass: PrettyButtonPlugin
      linux:
        pluginClass: PrettyButtonPlugin
      macos:
        pluginClass: PrettyButtonPlugin
      windows:
        pluginClass: PrettyButtonPluginCApi
      web:
        pluginClass: PrettyButtonWeb
        fileName: pretty_button_web.dart

